package dev.gr0mi4.ohealthinsights.drive

import java.time.Instant
import java.time.ZoneOffset
import java.time.format.DateTimeFormatter
import dev.gr0mi4.ohealthinsights.BuildConfig
import dev.gr0mi4.ohealthinsights.EngineExportResult

class ReportBuilder(
    private val metricsStore: MetricsStore,
) {
    fun buildMarkdown(
        summary: EngineExportResult,
        exportedAt: Instant,
        sessionWorkouts: List<WorkoutMetric>,
        warnings: List<String> = summary.warnings,
        reportDays: Int = 14,
    ): String {
        val recent = metricsStore.recentDays(reportDays)
        val includedWorkouts = sessionWorkouts.filter { it.includedInTotals }
        val excludedWorkouts = sessionWorkouts.filterNot { it.includedInTotals }
        val formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm 'UTC'").withZone(ZoneOffset.UTC)
        return buildString {
            appendLine("# OHealth Insights Report")
            appendLine()
            appendLine("- App version: ${BuildConfig.VERSION_NAME}")
            appendLine("- Exported at: ${formatter.format(exportedAt)}")
            appendLine("- Sync mode: ${summary.syncMode}")
            appendLine("- Raw records: ${summary.rawRecordCount}")
            appendLine("- Derived summaries: ${summary.derivedRecordCount}")
            appendLine("- Non-empty record types: ${summary.nonEmptyTypes}")
            appendLine()
            appendLine("## Last $reportDays days")
            appendLine()
            appendLine(
                "| Date | Steps (dedup) | Steps (OHealth) | Calories (kcal) | " +
                    "Workouts | Sleep (actual min) | Time in bed (min) |",
            )
            appendLine("| --- | ---: | ---: | ---: | ---: | ---: | ---: |")
            recent.forEach { day ->
                appendLine(
                    "| ${day.date} | ${day.stepsTotal ?: "—"} | ${day.stepsOHealth ?: "—"} | " +
                        "${formatDouble(day.totalCaloriesKcal)} | ${day.workoutCount} | " +
                        "${day.sleepMinutes ?: "—"} | ${day.timeInBedMinutes ?: "—"} |",
                )
            }
            if (includedWorkouts.isNotEmpty()) {
                appendLine()
                appendLine("## Workouts in this sync")
                appendLine()
                includedWorkouts.forEach { workout ->
                    appendLine(
                        "- ${workout.title ?: "Workout"}: " +
                            "${formatter.format(workout.startTime)} → ${formatter.format(workout.endTime)}, " +
                            "${formatDouble(workout.caloriesKcal)} kcal",
                    )
                }
            }
            if (excludedWorkouts.isNotEmpty()) {
                appendLine()
                appendLine("## Generic activity excluded from workout totals")
                appendLine()
                excludedWorkouts.forEach { workout ->
                    appendLine(
                        "- ${workout.title ?: "Workout"}: " +
                            "${formatter.format(workout.startTime)} → ${formatter.format(workout.endTime)}, " +
                            "${formatDouble(workout.caloriesKcal)} kcal " +
                            "(${workout.exclusionReason})",
                    )
                }
            }
            if (warnings.isNotEmpty()) {
                appendLine()
                appendLine("## Warnings")
                warnings.forEach { appendLine("- $it") }
            }
            appendLine()
            appendLine("---")
            appendLine("*Generated by OHealth Insights for ChatGPT / personal analysis.*")
        }
    }

    fun buildCsv(reportDays: Int = 90): String = buildString {
        appendLine(
            "date,steps_total,steps_ohealth,calories_kcal,workout_count," +
                "workout_calories_kcal,sleep_minutes,time_in_bed_minutes",
        )
        metricsStore.recentDays(reportDays).forEach { day ->
            appendLine(
                listOf(
                    day.date,
                    day.stepsTotal?.toString() ?: "",
                    day.stepsOHealth?.toString() ?: "",
                    day.totalCaloriesKcal?.toString() ?: "",
                    day.workoutCount,
                    day.workoutCaloriesKcal?.toString() ?: "",
                    day.sleepMinutes?.toString() ?: "",
                    day.timeInBedMinutes?.toString() ?: "",
                ).joinToString(","),
            )
        }
    }

    private fun formatDouble(value: Double?): String =
        if (value == null) "—" else "%.0f".format(value)
}
