package dev.gr0mi4.ohealthinsights.drive

import java.time.Instant
import java.time.ZoneOffset
import java.time.format.DateTimeFormatter
import dev.gr0mi4.ohealthinsights.BuildConfig
import dev.gr0mi4.ohealthinsights.EngineExportResult

class ReportBuilder(
    private val metricsStore: MetricsStore,
) {
    fun buildMarkdown(
        summary: EngineExportResult,
        exportedAt: Instant,
        sessionWorkouts: List<WorkoutMetric>,
        warnings: List<String> = summary.warnings,
        reportDays: Int = 14,
    ): String {
        val recent = metricsStore.recentDays(reportDays)
        val formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm 'UTC'").withZone(ZoneOffset.UTC)
        return buildString {
            appendLine("# OHealth Insights Report")
            appendLine()
            appendLine("- App version: ${BuildConfig.VERSION_NAME}")
            appendLine("- Exported at: ${formatter.format(exportedAt)}")
            appendLine("- Sync mode: ${summary.syncMode}")
            appendLine("- Raw records: ${summary.rawRecordCount}")
            appendLine("- Derived summaries: ${summary.derivedRecordCount}")
            appendLine("- Non-empty record types: ${summary.nonEmptyTypes}")
            appendLine()
            appendLine("## Analysis contract")
            appendLine()
            appendLine("- Canonical daily steps: `Steps (OHealth)` when present; use `Steps (dedup)` only as an explicit fallback/debug value.")
            appendLine("- Calories are summed from OHealth records only, bucketed by local calendar day, with per-workout summary records dropped so a session is not counted twice. They match the figure the OHealth app shows.")
            appendLine("- `Covered (min)` is how many minutes of the day carry a calorie record. A low value means the watch was off the wrist, not that the day was inactive; days with very different coverage are not comparable.")
            appendLine("- `In bed (min)` is time in bed, not time asleep: OHealth subtracts the awake segments it marks in its own app, and Health Connect never receives them. Expect it to read a few minutes above the watch.")
            appendLine("- `Wake (est)` is an estimate of night-time awakenings from heart rate alone. Use it for whether a night was settled or broken, never as sleep staging or as a count to report literally.")
            appendLine("- A row for the export day may be partial when the sync ran before the local day ended.")
            appendLine("- Raw exercise records are activity records, not automatically separate training sessions.")
            appendLine("- Generic `Workout` may be walking, warm-up/cool-down, or an adjacent fragment; `Freestyle workout` is semantically ambiguous.")
            appendLine("- Classify ambiguous sessions using duration, kcal/min, HR/HR zones, steps/step rate, distance, overlap/adjacency, context, and user-confirmed ground truth.")
            appendLine("- Separate deliberate training from light activity/everyday walking; if evidence is insufficient, keep the session unclassified rather than guessing.")
            appendLine("- Full interpretation rules: `docs/ANALYSIS_CONTRACT.md` in the ohealth-insights repository.")
            appendLine()
            appendLine("## Last $reportDays days")
            appendLine()
            appendLine("| Date | Steps (dedup) | Steps (OHealth) | Calories (OHealth) | Covered (min) | Workouts | In bed (min) | Wake (est) |")
            appendLine("| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: |")
            recent.forEach { day ->
                appendLine(
                    "| ${day.date} | ${day.stepsTotal ?: "—"} | ${day.stepsOHealth ?: "—"} | " +
                        "${formatDouble(day.caloriesOHealthKcal)} | ${day.caloriesCoveredMinutes ?: "—"} | " +
                        "${day.workoutCount} | ${day.sleepMinutes ?: "—"} | ${day.awakenings ?: "—"} |",
                )
            }
            if (sessionWorkouts.isNotEmpty()) {
                appendLine()
                appendLine("## Exercise records in this sync")
                appendLine()
                appendLine("*These are source exercise records and must not be interpreted as distinct training sessions without classification.*")
                appendLine()
                sessionWorkouts.forEach { workout ->
                    appendLine(
                        "- ${workout.title ?: "Workout"}: " +
                            "${formatter.format(workout.startTime)} → ${formatter.format(workout.endTime)}, " +
                            "${formatDouble(workout.caloriesKcal)} kcal",
                    )
                }
            }
            if (warnings.isNotEmpty()) {
                appendLine()
                appendLine("## Warnings")
                warnings.forEach { appendLine("- $it") }
            }
            appendLine()
            appendLine("---")
            appendLine("*Generated by OHealth Insights for ChatGPT / personal analysis.*")
        }
    }

    fun buildCsv(reportDays: Int = 90): String = buildString {
        appendLine("date,steps_total,steps_ohealth,calories_ohealth_kcal,calories_covered_minutes,workout_count,workout_calories_ohealth_kcal,time_in_bed_minutes,awakenings_estimated")
        metricsStore.recentDays(reportDays).forEach { day ->
            appendLine(
                listOf(
                    day.date,
                    day.stepsTotal?.toString() ?: "",
                    day.stepsOHealth?.toString() ?: "",
                    day.caloriesOHealthKcal?.toString() ?: "",
                    day.caloriesCoveredMinutes?.toString() ?: "",
                    day.workoutCount,
                    day.workoutCaloriesKcal?.toString() ?: "",
                    day.sleepMinutes?.toString() ?: "",
                    day.awakenings?.toString() ?: "",
                ).joinToString(","),
            )
        }
    }

    private fun formatDouble(value: Double?): String =
        if (value == null) "—" else "%.0f".format(value)
}
